"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Answers = { studyType?: "Bachillerato" | "Universidad" | "Otros estudios"; course?: string; university?: string; degree?: string; studies?: string; subjects: string[]; needType?: "PAU / Selectividad" | "Preparar un examen" | "Seguimiento durante el curso" | "Otra situación"; examTiming?: string; pauRegion?: string; otherNeed?: string; callPreference: boolean };
const initial: Answers = { subjects: [""], callPreference: false };

function Choice({ value, onClick }: { value: string; onClick: () => void }) {
  return <button className="choice" type="button" onClick={onClick}>{value}<span aria-hidden="true">↗</span></button>;
}

export function Diagnostic() {
  const router = useRouter(); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Answers>(initial); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const raw = sessionStorage.getItem("teselando:diagnostic"); const frame = requestAnimationFrame(() => { if (raw) setAnswers(JSON.parse(raw)); }); const onPop = (event: PopStateEvent) => setStep(Number(event.state?.diagnosticStep ?? 0)); addEventListener("popstate", onPop); return () => { cancelAnimationFrame(frame); removeEventListener("popstate", onPop); }; }, []);
  useEffect(() => { sessionStorage.setItem("teselando:diagnostic", JSON.stringify(answers)); }, [answers]);
  function move(next: number) { setError(""); setStep(next); history.pushState({ diagnosticStep: next }, "", location.href); }
  const needsPau = answers.studyType === "Bachillerato" && answers.course === "2.º";
  const summary = useMemo(() => [answers.course || answers.studyType, answers.subjects.filter(Boolean).join(", "), answers.needType === "Preparar un examen" ? answers.examTiming : answers.needType, answers.pauRegion].filter(Boolean).join(" · "), [answers]);
  async function finish() {
    const leadId = sessionStorage.getItem("teselando:lead"); if (!leadId) { setError("Primero necesitamos guardar tu teléfono."); return; }
    setSaving(true); setError("");
    try { const response = await fetch("/api/leads/diagnostic/", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ leadId, ...answers }) }); if (!response.ok) throw new Error(); sessionStorage.setItem("teselando:summary", summary); router.push("/solicitud/completada/"); } catch { setError("No hemos podido guardar tus respuestas. Inténtalo de nuevo."); setSaving(false); }
  }
  function chooseStudy(value: Answers["studyType"]) { setAnswers({ ...initial, studyType: value }); move(1); }
  return <div className="diagnostic"><div className="diagnostic-progress" aria-label="Progreso"><span className="done">Contacto ✓</span><span className={step <= 1 ? "active" : "done"}>Estudios</span><span className={step >= 2 && step < 4 ? "active" : step >= 4 ? "done" : ""}>Necesidad</span><span className={step === 4 ? "active" : ""}>Listo</span></div>
    {step === 0 && <div className="question"><p className="eyebrow">ESTUDIOS</p><h1>¿Qué estás estudiando?</h1><div className="choices"><Choice value="Bachillerato" onClick={() => chooseStudy("Bachillerato")} /><Choice value="Universidad" onClick={() => chooseStudy("Universidad")} /><Choice value="Otros estudios" onClick={() => chooseStudy("Otros estudios")} /></div></div>}
    {step === 1 && <div className="question"><p className="eyebrow">CONTEXTO ACADÉMICO</p>{answers.studyType === "Bachillerato" && <><h1>¿En qué curso estás?</h1><div className="choices"><Choice value="1.º" onClick={() => { setAnswers({ ...answers, course: "1.º" }); move(2); }} /><Choice value="2.º" onClick={() => { setAnswers({ ...answers, course: "2.º" }); move(2); }} /></div></>}{answers.studyType === "Universidad" && <><h1>Cuéntanos tu contexto académico</h1><label>Carrera<input value={answers.degree || ""} onChange={(e) => setAnswers({ ...answers, degree: e.target.value })} maxLength={120} /></label><label>Universidad<input value={answers.university || ""} onChange={(e) => setAnswers({ ...answers, university: e.target.value })} maxLength={120} /></label><label>Curso<select value={answers.course || ""} onChange={(e) => setAnswers({ ...answers, course: e.target.value })}><option value="">Selecciona</option>{["1.º", "2.º", "3.º", "4.º", "5.º+"].map(v => <option key={v}>{v}</option>)}</select></label><button className="button" onClick={() => answers.degree && answers.university && answers.course ? move(2) : setError("Completa los tres campos.")}>Continuar</button></>}{answers.studyType === "Otros estudios" && <><h1>¿Qué estudias?</h1><label>Estudios<input value={answers.studies || ""} onChange={(e) => setAnswers({ ...answers, studies: e.target.value })} maxLength={160} /></label><button className="button" onClick={() => answers.studies ? move(2) : setError("Cuéntanos qué estudias.")}>Continuar</button></>}<button className="back-link" onClick={() => move(0)}>Volver</button></div>}
    {step === 2 && <div className="question"><p className="eyebrow">ASIGNATURA</p><h1>¿Con qué asignatura necesitas ayuda?</h1>{answers.subjects.map((subject, index) => <label key={index}>Asignatura {index + 1}<input value={subject} maxLength={100} onChange={(e) => { const subjects = [...answers.subjects]; subjects[index] = e.target.value; setAnswers({ ...answers, subjects }); }} /></label>)}{answers.subjects.length < 4 && <button className="add-link" onClick={() => setAnswers({ ...answers, subjects: [...answers.subjects, ""] })}>+ Añadir otra asignatura</button>}<button className="button" onClick={() => answers.subjects.some(Boolean) ? move(3) : setError("Añade al menos una asignatura.")}>Continuar</button><button className="back-link" onClick={() => move(1)}>Volver</button></div>}
    {step === 3 && <div className="question"><div className="subject-confirm">✓ {answers.subjects.filter(Boolean).join(" · ")}</div><p className="eyebrow">NECESIDAD</p><h1>¿Qué necesitas ahora?</h1><div className="choices">{needsPau && <Choice value="Preparar PAU / Selectividad" onClick={() => { setAnswers({ ...answers, needType: "PAU / Selectividad" }); move(4); }} />}<Choice value="Preparar un examen" onClick={() => { setAnswers({ ...answers, needType: "Preparar un examen" }); move(4); }} /><Choice value="Seguimiento durante el curso" onClick={() => { setAnswers({ ...answers, needType: "Seguimiento durante el curso" }); move(4); }} /><Choice value="Otra situación" onClick={() => { setAnswers({ ...answers, needType: "Otra situación" }); move(4); }} /></div><button className="back-link" onClick={() => move(2)}>Volver</button></div>}
    {step === 4 && <div className="question"><p className="eyebrow">ÚLTIMO DETALLE</p>{answers.needType === "Preparar un examen" && <><h1>¿Cuándo es?</h1><div className="choices">{["Esta semana", "En 1-2 semanas", "En más de 2 semanas"].map(v => <Choice key={v} value={v} onClick={() => setAnswers({ ...answers, examTiming: v })} />)}</div></>}{answers.needType === "PAU / Selectividad" && <><h1>¿En qué comunidad te examinas?</h1><label>Comunidad<input value={answers.pauRegion || ""} onChange={(e) => setAnswers({ ...answers, pauRegion: e.target.value })} maxLength={80} /></label></>}{answers.needType === "Otra situación" && <><h1>Cuéntanos brevemente</h1><label>Situación<textarea value={answers.otherNeed || ""} onChange={(e) => setAnswers({ ...answers, otherNeed: e.target.value })} maxLength={240} /></label></>}<div className="summary-preview">{summary}</div><button className="button" disabled={saving} onClick={() => { if (answers.needType === "Preparar un examen" && !answers.examTiming) return setError("Selecciona cuándo es el examen."); if (answers.needType === "PAU / Selectividad" && !answers.pauRegion) return setError("Indica tu comunidad."); if (answers.needType === "Otra situación" && !answers.otherNeed) return setError("Cuéntanos brevemente la situación."); finish(); }}>{saving ? "Guardando…" : "Continuar"}</button><button className="back-link" onClick={() => move(3)}>Volver</button></div>}
    {error && <p className="diagnostic-error" role="alert">{error}</p>}
  </div>;
}
